#  environment document

name: rland3
channels:
  - conda-forge
  
dependencies:
  - r-recommended
  - r-irkernel
  - Jupyter
  - r-devtools
  - r-readxl
  - r-writexl
  - r-dplyr
  - r-readxl
  - r-writexl
  - r-dplyr
