name: Sanity
on: [push]

jobs:
  SanityOnMulti:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11']
        include:
          - python-version: '3.10'
            tox-python: "py310"
          - python-version: '3.11'
            tox-python: 'py311'
          - os: windows-latest
            python: .venv/Scripts/python.exe
          - os: ubuntu-latest
            python: .venv/bin/python
          - os: macos-latest
            python: .venv/bin/python
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: ci
          channels: conda-forge
      - run: python -m pip install tox nibabel
      - run: >
          python -m tox -e ${{ matrix.tox-python }}
          -- tests/test_multi.py

  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          auto-activate-base: false
          activate-environment: ci
          python-version: '3.11'
      - run: python -m pip install wheel  
      - run: python -m pip install pycodestyle "pytest<8.1"
      - run: python setup.py lint

  Sphinx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          auto-activate-base: false
          activate-environment: ci
          python-version: '3.10'
      - run: python -m pip install wheel
      - run: python setup.py bdist_wheel
      - run: python -m pip install ./dist/*.whl
      - run: python -m pip install sphinx nibabel
      - run: python setup.py apidoc
      - run: python setup.py build_sphinx -W
      - name: Publish Docs to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/sphinx/html  